SET(INSTALL_BINDIR bin/plugins)
IF(WIN32)
    SET(INSTALL_LIBDIR bin/plugins)
    SET(INSTALL_ARCHIVEDIR lib/plugins)
ELSE()
    SET(INSTALL_LIBDIR ${CMAKE_INSTALL_LIBDIR}/plugins)
    SET(INSTALL_ARCHIVEDIR ${CMAKE_INSTALL_LIBDIR}/plugins)
ENDIF()

INSTALL(
    TARGETS ${LIB_NAME}
    EXPORT openig-targets
    RUNTIME DESTINATION ${INSTALL_BINDIR} COMPONENT libopenig
    LIBRARY DESTINATION ${INSTALL_LIBDIR} COMPONENT libopenig
    ARCHIVE DESTINATION ${INSTALL_ARCHIVEDIR} COMPONENT libopenig-dev
)


